apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-ms-movies
  namespace: dev
  labels:
    app: backend-ms-movies
spec:
  replicas: 2
  revisionHistoryLimit: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: backend-ms-movies
  template:
    metadata:
      labels:
        app: backend-ms-movies
        version: "1.07"
    spec:
      containers:
        - name: backend-ms-movies
          image: zebolhd/qa-backend-ms-movies:latest
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "150Mi"
              cpu: "200m"
          imagePullPolicy: Always
          envFrom:
            - configMapRef:
                name: qa-config
            - secretRef:
                name: qa-secret
          ports:
            - containerPort: 5000

---
apiVersion: v1
kind: Service
metadata:
  name: backend-ms-movies
  namespace: dev
spec:
  selector:
    app: backend-ms-movies
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 31500
  type: NodePort
